import Newsletter from '../models/Newsletter.js';import Post from '../models/Post.js';import {sendMail} from '../utils/mailer.js';import {ensureUnsubscribeToken,sendPostAnnouncement} from '../utils/newsletter.js';
export async function subscribe(req,res){const email=typeof req.body.email==='string'?req.body.email.trim().toLowerCase():'';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({message:'Enter a valid email address'});try{await Newsletter.create({email});res.status(201).json({message:'Subscribed'})}catch(e){if(e.code===11000)return res.json({message:'Already subscribed'});throw e}}
export async function listSubscribers(req,res){res.json({subscribers:await Newsletter.find().select('-unsubscribeToken').sort({createdAt:-1})})}
export async function sendNewsletter(req,res){const subject=typeof req.body.subject==='string'?req.body.subject.trim():'';const html=typeof req.body.html==='string'?req.body.html:'';if(!subject||subject.length>200||!html||html.length>100000)return res.status(400).json({message:'A subject and newsletter body are required'});const subs=await Newsletter.find();const apiUrl=(process.env.API_PUBLIC_URL||'http://localhost:5000').replace(/\/+$/,'');const results=await Promise.allSettled(subs.map(async subscriber=>{const token=await ensureUnsubscribeToken(subscriber);return sendMail(subscriber.email,subject,`${html}<hr><p><small><a href="${apiUrl}/api/newsletter/unsubscribe/${token}">Unsubscribe from these emails</a></small></p>`)}));const sent=results.filter(result=>result.status==='fulfilled'&&result.value).length;const failed=results.length-sent;if(failed)return res.status(503).json({message:'Some newsletter emails could not be delivered',sent,failed});res.json({sent})}
export async function sendLatestPost(req,res){
    const post=await Post.findOne({status:'published'}).sort({publishedAt:-1,createdAt:-1}).select('_id');
    if(!post)return res.status(404).json({message:'There are no published posts to send.'});
    const result=await sendPostAnnouncement(post._id);
    if(result.status==='already-sent')return res.status(409).json({message:'The latest post has already been emailed to subscribers.'});
    if(result.status==='sending')return res.status(409).json({message:'The latest post email is already being sent.'});
    if(result.status==='no-subscribers')return res.status(400).json({message:'There are no newsletter subscribers yet.'});
    if(result.status==='failed')return res.status(503).json({message:'Some post emails could not be delivered. Check SMTP configuration and try again.',sent:result.sent,failed:result.failed});
    if(result.status!=='sent')return res.status(409).json({message:'The latest post is no longer available to send.'});
    res.json({sent:result.sent});
}
export async function confirmUnsubscribe(req,res){if(!/^[a-f0-9]{64}$/.test(req.params.token))return res.status(404).type('text').send('Unsubscribe link not found.');res.type('html').send(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Unsubscribe | PrinelvaBlog</title><body style="font:16px system-ui;max-width:36rem;margin:4rem auto;padding:0 1rem"><h1>Unsubscribe from PrinelvaBlog emails</h1><p>Confirm below to stop receiving newsletter and new-post emails.</p><form method="post" action="/api/newsletter/unsubscribe/${req.params.token}"><button style="background:#4f46e5;color:white;border:0;border-radius:8px;padding:.75rem 1rem;font:inherit">Confirm unsubscribe</button></form></body></html>`)}
export async function unsubscribe(req,res){const token=req.params.token;if(!/^[a-f0-9]{64}$/.test(token))return res.status(404).type('text').send('Unsubscribe link not found.');const result=await Newsletter.deleteOne({unsubscribeToken:token});res.type('text').send(result.deletedCount?'You have been unsubscribed.':'This unsubscribe link is invalid or has already been used.')}
